### ISSUE TITLE
mc and ps error

### ISSUE THREAD

**Issue by luigiScarso** [darlinghq/darling#168]
I have compiled and installed darling
commit 40ff26128a13d0e9d371609c9814d5c4ef95d369
With darling shell I have
Darling [~]# ps
Failure calling sysctl: Not a directory
I was able to install mc, but I have
Darling [~]# mc
dyld: Cannot execute binary file: Symbol not found: _kCFPreferencesCurrentApplication

Have I missed something ?

Thank you very much
## 

luigi

**Comment by LubosD** [comment]
mc: I forgot to commit one change (CFPreferences were being moved into CoreFoundation repo). Should be fixed now.

ps doesn't work, because the needed sysctl() interface isn't implemented yet. See https://github.com/darlinghq/darling/blob/master/src/kernel/emulation/linux/misc/sysctl.c#L170

**Comment by luigiScarso** [comment]
With commit f3ed7c5263f15997b6769cbd02f803c3000f177c
I still have 
Darling [~]# mc
dyld: Cannot execute binary file: Symbol not found: _kCFPreferencesCurrentApplication

**Comment by LubosD** [comment]
And have there been actual build changes? Git should automatically update the subrepository...

**Comment by LubosD** [comment]
This is what you should see in your build directory:
```
$ readelf -Ws ./src/CFF/libCFF.so | grep kCFPreferencesCurrentApplication@@DARWIN
  5801: 00000000008c0578     8 OBJECT  GLOBAL DEFAULT   17 kCFPreferencesCurrentApplication@@DARWIN
```

**Comment by luigiScarso** [comment]
hm no,
readelf -Ws ./src/CFF/libCFF.so | grep kCFPreferencesCurrentApplication@@DARWIN
gives nothing and the error with mc is still the same.

I'm currently using
commit 65dee5fdb74ec4b9bc08702a183a138de450c975
Author: Lubos Dolezel <lubos@dolezel.info>
Date:   Tue Oct 11 15:52:18 2016 +0200

    Force the use of Bash in 'darling' (resolves #169)

Could be related with 
commit 9dc2c948b572974654b5acbcff5cbe83a89544ab
Author: Lubos Dolezel <lubos@dolezel.info>
Date:   Thu Oct 6 23:20:16 2016 +0200

    Get rid of doubly defined CFPreferences
?

**Comment by LubosD** [comment]
If you go into src/external/corefoundation, the commit in there should be:
```
commit 5eb9d274df064cb4d55df596d952dd61d6d3a55e
Author: Lubos Dolezel <lubos@dolezel.info>
Date:   Tue Oct 11 11:43:06 2016 +0200

    Fix CFPreferences constants
```

If it is not, then you probably didn't clone Darling with the `--recursive` option and will have to manage submodules manually through a combination of `git fetch` and `git submodule update`.

**Comment by luigiScarso** [comment]
I have cloned the repo, and now It's ok.
